{
 "title": "DEMO CLOSED LOOP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from COMPONENTS with key=\"SHORTNAME\""
   }
  ]
 },
 "panels": [
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT last(\"idle_cpu\") FROM \"COMPONENTS\" WHERE \"SHORTNAME\"::tag=~ /^$rtr$/ AND $timeFilter group by VERSION, MODEL, SHORTNAME",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "component_name::tag", "operator": "=~", "value": "/^$comp_name$/" },
      { "condition": "AND", "key": "property_name::tag", "operator": "=~", "value": "/^$prop_name$/" }
     ]
    }
   ]
  },
  {
   "title": "LAST ERRORS (15mins)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ALARM_TYPE",
     "measurement": "ALARMING",
     "query": "SELECT count(\"exception\") FROM \"ALARMING\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and time > now()-15m  group by \"ALARM_TYPE\" fill(0)",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Current FPC CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT \"linecard_cpu\" FROM \"COMPONENTS\" WHERE \"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /FPC.*/ AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "FPC0" }
     ]
    }
   ]
  },
  {
   "title": "CHASSIS ALARMS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "/system/alarms/alarm/id" ], "type": "tag" }
     ],
     "measurement": "JUNOS_ALARMS",
     "query": "select count(last) from (SELECT last(\"alarm_text\") FROM \"JUNOS_ALARMS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter GROUP BY \"/system/alarms/alarm/id\")",
     "select": [
      [
       { "params": [ "alarm_text" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "/system/alarms/alarm/id" ], "type": "tag" }
     ],
     "measurement": "JUNOS_ALARMS",
     "query": "select count(last) from (SELECT last(\"alarm_text_net\") FROM \"JUNOS_ALARMS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter group by alarm_id_net)",
     "select": [
      [
       { "params": [ "alarm_text" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Current RE0 CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT 100 - \"idle_cpu\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine0|RE0/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE0 Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT \"buffer_usage\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine0|RE0/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current FPC Heap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT \"linecard_memory\" FROM \"COMPONENTS\" WHERE \"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /FPC.*/ AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "FPC0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE1 CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT 100 - \"idle_cpu\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine1|RE1/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE1 Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT \"buffer_usage\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine1|RE1/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Syslog - OnChange - last 15 minutes only",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JUNOS_EVENTS",
     "query": "SELECT * FROM \"JUNOS_EVENTS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/) AND time>now()-15m and path='/junos/events/event'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<h2><center>- Alarming -</center><h2>"
   }
  },
  { "title": "Alarming - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Chassis Alarms",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "measurement": "JUNOS_ALARMS",
     "query": "SELECT last(\"alarm_severity\"), last(\"alarm_resource\"), last(\"alarm_time\")/1000000, last(\"alarm_text\") FROM \"JUNOS_ALARMS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and  $timeFilter GROUP BY \"/system/alarms/alarm/id\"",
     "select": [
      [
       { "params": [ "alarm_severity" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_resource" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_time" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "measurement": "JUNOS_ALARMS",
     "query": "SELECT last(\"alarm_severity_net\"), last(\"alarm_resource_net\"), last(\"alarm_time_net\"), last(\"alarm_text_net\") FROM \"JUNOS_ALARMS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and  $timeFilter GROUP BY \"alarm_id_net\"",
     "select": [
      [
       { "params": [ "alarm_severity" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_resource" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_time" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecard Errors",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "$tag_cmerror_name,COUNT",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "JUNOS_CMERROR",
     "query": "SELECT last( \"cmerror_count\") FROM \"JUNOS_CMERROR\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,UPDATE",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "JUNOS_CMERROR",
     "query": "SELECT last( \"cmerror_update\") FROM \"JUNOS_CMERROR\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,CLEAR",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "JUNOS_CMERROR",
     "query": "SELECT last( \"cmerror_clear\") FROM \"JUNOS_CMERROR\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,SLOT",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "JUNOS_CMERROR",
     "query": "SELECT last( \"cmerror_slot\")+0.1 FROM \"JUNOS_CMERROR\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,DELTA",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "JUNOS_CMERROR",
     "query": "SELECT  last( \"cmerror_clear\")-last( \"cmerror_update\")+0.1 FROM \"JUNOS_CMERROR\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<h2><center>- CPU/MEM -</center><h2>"
   }
  },
  {
   "title": "CPU / Memory for Components & Processes - $rtr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Routing-engine CPU",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT 100-\"idle_cpu\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Routing-Engine Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Mem $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "query": "SELECT \"buffer_usage\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and component_name=~/.*outing.*|RE.*/ GROUP BY \"component_name\"",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecards CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "query": "SELECT \"linecard_cpu\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND component_name=~ /^FPC.*/ and $timeFilter GROUP BY component_name",
     "select": [
      [
       { "params": [ "linecard_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecards Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Heap memory $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "query": "SELECT \"linecard_memory\" FROM \"COMPONENTS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter AND component_name=~ /^FPC.*/ GROUP BY \"component_name\"",
     "select": [
      [
       { "params": [ "linecard_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "SYSTEM CPU (only >0%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_process_name - (PID $tag_process_pid)",
     "query": "SELECT \"process_cpu_utilization\" FROM \"SYSTEM\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and $timeFilter GROUP BY \"process_name\", \"process_pid\""
    }
   ]
  },
  {
   "title": "CORE Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "query": "SELECT \"cpu_utilization\" FROM \"SYSTEM\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND \"cpu_utilization\"!=0 and $timeFilter GROUP BY \"name\", \"process_pid\"",
     "select": [
      [
       { "params": [ "core_cpu_instant" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "PROCESS Memory (only >32MB)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_process_name - (PID $tag_process_pid)",
     "query": "SELECT \"process_memory_usage\" FROM \"SYSTEM\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and $timeFilter GROUP BY \"process_name\", \"process_pid\" fill(0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 },
   "options": {
    "content": "<h2><center>- Fabric -</center><h2>"
   }
  },
  { "title": "Fabric - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Fabric Drops PPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Fabric Drops pps $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "select": [
      [
       { "params": [ "fabric_drops_pkts_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "In Fabric PPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "In Fabric pps $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "select": [
      [
       { "params": [ "fabric_input_pkts_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Out Fabric PPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Out Fabric pps $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "COMPONENTS",
     "select": [
      [
       { "params": [ "fabric_output_pkts_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  }
 ]
}